kind: ConfigMap
apiVersion: v1
metadata:
  name: huawei-csi-configmap
  namespace: kube-system
data:
  csi.json: |
    {
        "backends": [
            {
                "storage": "fusionstorage-nas",
                "name": "***",
                "url": "https://*.*.*.*:28443",
                "user": "***",
                "password": "***",
                "pools": ["***"],
                "parameters": {"portal": "*.*.*.*"}
            }
        ]
    }
