kind: ConfigMap
apiVersion: v1
metadata:
  name: huawei-csi-configmap
  namespace: kube-system
data:
  csi.json: |
    {
        "backends": [
            {
                "storage": "oceanstor-nas",
                "product": "***",
                "name": "***",
                "urls": [
                    "https://*.*.*.*:8088/deviceManager/rest"
                ],
                "user": "***",
                "password": "***",
                "pools": ["***"],
                "parameters": {"portal": "*.*.*.*"}
            }
        ]
    }
