{{ if .Values.CSIDriverObject.isCreate }}
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
    name: {{ .Values.csiDriver.driverName }}
    labels:
        provisioner: csi.huawei.com
spec:
    attachRequired: {{ .Values.CSIDriverObject.attachRequired }}
  {{ if ne .Values.CSIDriverObject.fsGroupPolicy "null" }}
    fsGroupPolicy: {{ .Values.CSIDriverObject.fsGroupPolicy }}
  {{ end }}
{{ end }}