apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
    name: {{ .Values.csiDriver.driverName }}
spec:
    attachRequired: {{ .Values.attachRequired }}
    fsGroupPolicy: {{ .Values.fsGroupPolicy }}
