---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    provisioner: csi.huawei.com
  name: huawei-csi-node
  namespace: {{ .Values.kubernetes.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    provisioner: csi.huawei.com
  name: huawei-csi-driver-registrar-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: huawei-csi-driver-registrar-runner
subjects:
  - kind: ServiceAccount
    name: huawei-csi-node
    namespace: {{ .Values.kubernetes.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    provisioner: csi.huawei.com
  name: huawei-csi-driver-registrar-runner
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
      - persistentvolumeclaims
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    provisioner: csi.huawei.com
  name: huawei-csi-node-runner
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - update
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
  - apiGroups:
      - "xuanwu.huawei.io"
    resources:
      - storagebackendclaims
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    provisioner: csi.huawei.com
  name: huawei-csi-node-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: huawei-csi-node-runner
subjects:
  - kind: ServiceAccount
    name: huawei-csi-node
    namespace: {{ .Values.kubernetes.namespace }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    provisioner: csi.huawei.com
  name: huawei-csi-node
  namespace: {{ .Values.kubernetes.namespace }}
spec:
  selector:
    matchLabels:
      app: huawei-csi-node
      provisioner: csi.huawei.com
  template:
    metadata:
      labels:
        app: huawei-csi-node
        provisioner: csi.huawei.com
    spec:
      {{ if .Values.node.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.node.nodeSelector | nindent 8 }}
      {{ end }}
      {{ if .Values.node.tolerations }}
      tolerations:
      {{- toYaml .Values.node.tolerations | nindent 6 }}
      {{ end }}
      containers:
        - name: liveness-probe
          args:
            - "--csi-address=/csi/csi.sock"
            - "--health-port=9800"
          image: {{ .Values.images.sidecar.livenessProbe }}
          imagePullPolicy: {{ .Values.sidecarImagePullPolicy }}
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: csi-node-driver-registrar
          args:
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path={{ .Values.kubeletConfigDir }}/plugins/csi.huawei.com/csi.sock"
          image: {{ .Values.images.sidecar.registrar }}
          imagePullPolicy: {{ .Values.sidecarImagePullPolicy }}
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /registration
              name: registration-dir
        - name: huawei-csi-driver
          image: {{ required "Must provide the CSI node service node image." .Values.images.huaweiCSIService }}
          imagePullPolicy: {{ .Values.huaweiImagePullPolicy }}
          args:
            - "--endpoint={{ .Values.csiDriver.endpoint }}"
            - "--driver-name={{ .Values.csiDriver.driverName }}"
            - "--connector-threads={{ .Values.csiDriver.connectorThreads }}"
            - "--volume-use-multipath={{ .Values.csiDriver.volumeUseMultipath }}"
            {{ if .Values.csiDriver.volumeUseMultipath }}
            - "--scsi-multipath-type={{ .Values.csiDriver.scsiMultipathType }}"
            - "--nvme-multipath-type={{ .Values.csiDriver.nvmeMultipathType }}"
            {{ end }}
            - "--scan-volume-timeout={{ .Values.csiDriver.scanVolumeTimeout }}"
            - "--logging-module={{ .Values.csiDriver.nodeLogging.module }}"
            - "--log-level={{ .Values.csiDriver.nodeLogging.level }}"
            {{ if eq .Values.csiDriver.nodeLogging.module "file" }}
            - "--log-file-dir={{ .Values.csiDriver.nodeLogging.fileDir }}"
            - "--log-file-size={{ .Values.csiDriver.nodeLogging.fileSize }}"
            - "--max-backups={{ .Values.csiDriver.nodeLogging.maxBackups }}"
            {{ end }}
            {{ if .Values.node.maxVolumesPerNode }}
            - "--max-volumes-per-node={{ .Values.node.maxVolumesPerNode }}"
            {{ end }}
          env:
            - name: CSI_NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CSI_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - rm -f /csi/csi.sock
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 3
          ports:
            - containerPort: 9800
              name: healthz
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: {{ .Values.kubeletConfigDir }}
              mountPropagation: Bidirectional
              name: pods-dir
            - mountPath: /etc
              name: etc-dir
            - mountPath: /var/log
              name: log-dir
            - mountPath: /dev
              mountPropagation: HostToContainer
              name: dev-dir
            - mountPath: /var/lib/iscsi
              name: iscsi-dir
      hostNetwork: true
      hostPID: true
      serviceAccountName: huawei-csi-node
      volumes:
        - hostPath:
            path: {{ .Values.kubeletConfigDir }}/plugins/csi.huawei.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: {{ .Values.kubeletConfigDir }}/plugins_registry
            type: Directory
          name: registration-dir
        - hostPath:
            path: {{ .Values.kubeletConfigDir }}
            type: Directory
          name: pods-dir
        - hostPath:
            path: /etc
            type: Directory
          name: etc-dir
        - hostPath:
            path: /dev
            type: Directory
          name: dev-dir
        - hostPath:
            path: /var/lib/iscsi
          name: iscsi-dir
        - hostPath:
            path: /var/log/
            type: Directory
          name: log-dir