
---
version: 2.0

# 构建环境


# 构建参数定义, 构建脚本可从环境变量中读取使用这些参数
params:
  - name: upload_to_Cloudcmc
    value: 'false'
  - name: upload_to_Enterprisecmc
    value: 'false'
  - name: RELEASE_VER
    value: 2.3.2
  - name: VER
    value: 2.2.13.4
  - name: PLATFORM
    value: X86
  - name: esdk_ci_branch
    value: master
  - name: DRCSI_branch
    value: master
  - name: dockerimg
    value: 'szvecr02.his.huawei.com:80/ecr-build/esdk_suse_x86_12sp5:2.1.RC1'


env:
  resource:
      type: docker
      image: ${dockerimg}
      resource_class: 4U4G
      pool: docker-gz-x86-ondocker-16u-01

steps:
  PRE_BUILD:
    - checkout:
        path: eSDK_Enterprise_Storage_Kubernetes
    - codehub:
        url: https://codehub-dg-y.huawei.com/esdk/esdk_public/esdk_ci.git
        branch: ${esdk_ci_branch}
        path: esdk_ci
    - codehub:
        url: https://codehub-dg-y.huawei.com/esdk/XuanWu/Public/DRCSI/DRCSI.git
        branch: ${DRCSI_branch}
        path: DRCSI
  BUILD:
    - build_execute:
        command: sh eSDK_Enterprise_Storage_Kubernetes/CI/build.sh ${RELEASE_VER} ${VER} ${PLATFORM};echo "buildVersion=${eSDK_version}.$(date "+%Y%m%d%H%M%S")" > buildInfo.properties
        accelerate: false
        check: true
  POST_BUILD:
    - get_build_metadata
    - upload_cloud_artifact:
        file_path: 'eSDK_Enterprise_Storage_Kubernetes/*.zip*'
    - version_set
    - when:
        condition: upload_to_Cloudcmc == 'true'
        steps:
          - get_build_metadata
          - artget:
              artifact_type: cmcbinary
              action: push
              dependency: eSDK_Enterprise_Storage_Kubernetes/CI/conf/cmc_dependency.xml
              version_output_path: .
              username: ${cmc_username}
              password: ${cmc_password}
              agent: .
              cache: /home/
              add_source_code: true
              params: {'version':'${Cloudversion}','dir':'eSDK_Enterprise_Storage_Kubernetes/eSDK_Huawei_Storage*.zip*','dist':'${dist}','offering':'eSDK Cloud Storage Plugins'}
          - get_build_metadata
    - when:
        condition: upload_to_Enterprisecmc == 'true'
        steps:
          - get_build_metadata
          - artget:
              artifact_type: cmcbinary
              action: push
              dependency: eSDK_Enterprise_Storage_Kubernetes/CI/conf/cmc_dependency.xml
              version_output_path: .
              username: ${cmc_username}
              password: ${cmc_password}
              agent: .
              cache: /home/
              add_source_code: true
              params: {'version':'${Enterpriseversion}','dir':'eSDK_Enterprise_Storage_Kubernetes/eSDK_Huawei_Storage*.zip*','dist':'${dist}','offering':'eSDK Enterprise Storage Plugins'}
          - get_build_metadata

