
---
version: 2.0

# 构建环境


# 构建参数定义, 构建脚本可从环境变量中读取使用这些参数
params:
  - name: upload_to_Cloudcmc
    value: 'false'
  - name: upload_to_Enterprisecmc
    value: 'false'
  - name: RELEASE_VER
    value: 2.3.2
  - name: VER
    value: 2.2.13.4
  - name: PLATFORM
    value: X86
  - name: dockerimg
    value: 'szvecr02.his.huawei.com:80/ecr-build/esdk_suse_x86_12sp5:2.1.RC1'


env:
  resource:
      type: docker
      image: ${dockerimg}
      resource_class: 4U4G
      pool: eks-build-x86-gz-kunpeng-ondocker-16u-02

steps:
  PRE_BUILD:
    - checkout
  BUILD:
    - build_execute:
        command: sh CI/build.sh ${RELEASE_VER} ${VER} ${PLATFORM};echo "buildVersion=${eSDK_version}.$(date "+%Y%m%d%H%M%S")" > buildInfo.properties
        accelerate: false
        check: true
  POST_BUILD:
    - get_build_metadata
    - upload_cloud_artifact:
        file_path: '*.zip'
    - version_set
    - when:
        condition: upload_to_Cloudcmc == 'true'
        steps:
          - get_build_metadata
          - artget:
              artifact_type: cmcbinary
              action: push
              dependency: CI/conf/cmc_dependency.xml
              version_output_path: .
              username: ${cmc_username}
              password: ${cmc_password}
              agent: .
              cache: /home/
              add_source_code: true
              params: {'version':'${Cloudversion}','dir':'eSDK_Huawei_Storage*.zip','dist':'${dist}','offering':'eSDK Cloud Storage Plugins'}
          - get_build_metadata
    - when:
        condition: upload_to_Enterprisecmc == 'true'
        steps:
          - get_build_metadata
          - artget:
              artifact_type: cmcbinary
              action: push
              dependency: CI/conf/cmc_dependency.xml
              version_output_path: .
              username: ${cmc_username}
              password: ${cmc_password}
              agent: .
              cache: /home/
              add_source_code: true
              params: {'version':'${Enterpriseversion}','dir':'eSDK_Huawei_Storage*.zip','dist':'${dist}','offering':'eSDK Enterprise Storage Plugins'}
          - get_build_metadata

