apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    provisioner: csi.huawei.com
  name: huawei-csi-node
  namespace: huawei-csi
spec:
  selector:
    matchLabels:
      app: huawei-csi-node
      provisioner: csi.huawei.com
  template:
    metadata:
      labels:
        app: huawei-csi-node
        provisioner: csi.huawei.com
    spec:
      containers:
        - args:
            - --csi-address=/csi/csi.sock
            - --health-port=9800
          image: quay.io/k8scsi/livenessprobe:v0.4.1
          imagePullPolicy: IfNotPresent
          name: liveness-probe
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi.huawei.com/csi.sock
          image: quay.io/k8scsi/driver-registrar:v0.4.2
          imagePullPolicy: IfNotPresent
          name: csi-node-driver-registrar
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /registration
              name: registration-dir
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
        - name: huawei-csi-driver
          image: huawei-csi:*.*.*
          imagePullPolicy: IfNotPresent
          args:
            - "--endpoint=/csi/csi.sock"
            - "--containerized"
            - "--driver-name=csi.huawei.com"
          env:
            - name: CSI_NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - rm -f /csi/csi.sock
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 3
          ports:
            - containerPort: 9800
              name: healthz
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
              name: pods-dir
            - mountPath: /etc
              name: etc-dir
            - mountPath: /var/log
              name: log-dir
            - mountPath: /dev
              mountPropagation: HostToContainer
              name: dev-dir
            - mountPath: /var/lib/iscsi
              name: iscsi-dir
            - mountPath: /etc/huawei
              name: config-map
            - mountPath: /etc/huawei/secret
              name: secret
      hostNetwork: true
      hostPID: true
      serviceAccountName: huawei-csi-node
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi.huawei.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/plugins/
            type: DirectoryOrCreate
          name: registration-dir
        - hostPath:
            path: /var/lib/kubelet
            type: Directory
          name: pods-dir
        - hostPath:
            path: /etc
            type: Directory
          name: etc-dir
        - hostPath:
            path: /dev
            type: Directory
          name: dev-dir
        - hostPath:
            path: /var/lib/iscsi
          name: iscsi-dir
        - hostPath:
            path: /var/log/
            type: Directory
          name: log-dir
        - configMap:
            name: huawei-csi-configmap
          name: config-map
        - name: secret
          secret:
            secretName: huawei-csi-secret
