apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    provisioner: csi.huawei.com
  name: huawei-csi-controller
  namespace: huawei-csi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huawei-csi-controller
      provisioner: csi.huawei.com
  template:
    metadata:
      labels:
        app: huawei-csi-controller
        provisioner: csi.huawei.com
    spec:
      containers:
        - args:
            - --csi-address=/csi/csi.sock
            - --health-port=9808
          image: quay.io/k8scsi/livenessprobe:v0.4.1
          imagePullPolicy: IfNotPresent
          name: liveness-probe
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - args:
            - --csi-address=$(ADDRESS)
            - --connection-timeout=6h
            - --provisioner=csi.huawei.com
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          image: quay.io/k8scsi/csi-provisioner:v0.4.2
          imagePullPolicy: IfNotPresent
          name: csi-provisioner
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - args:
            - --csi-address=$(ADDRESS)
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          image: quay.io/k8scsi/csi-attacher:v0.4.2
          imagePullPolicy: IfNotPresent
          name: csi-attacher
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: huawei-csi-driver
          image: huawei-csi:*.*.*
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --controller
            - --containerized
            - --backend-update-interval=120
            - --driver-name=csi.huawei.com
          env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 3
          ports:
            - containerPort: 9808
              name: healthz
              protocol: TCP
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/log
              name: log
            - mountPath: /etc/huawei
              name: config-map
            - mountPath: /etc/huawei/secret
              name: secret
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
      hostNetwork: true
      serviceAccount: huawei-csi-controller
      volumes:
        - emptyDir: null
          name: socket-dir
        - hostPath:
            path: /var/log/
            type: Directory
          name: log
        - configMap:
            name: huawei-csi-configmap
          name: config-map
        - name: secret
          secret:
            secretName: huawei-csi-secret
