kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mypvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  storageClassName: mysc
  resources:
    requests:
      storage: 100Gi
