---
kind: Service
apiVersion: v1
metadata:
  name: external-provisioner
  labels:
    app: external-provisioner
spec:
  selector:
    app: external-provisioner
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: external-provisioner
spec:
  serviceName: external-provisioner
  replicas: 1
  template:
    metadata:
      labels:
        app: external-provisioner
    spec:
      serviceAccount: csi-provisioner
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.0.1
          args:
            - "--provisioner=huawei"
            - "--csi-address=/csi/csi.sock"
          imagePullPolicy: "IfNotPresent"
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "touch /csi/provider_running"]
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -f /csi/provider_running"]
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/huawei.csi.driver
            type: Directory