kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: node-driver-registrar
spec:
  selector:
    matchLabels:
      app: node-driver-registrar
  template:
    metadata:
      labels:
        app: node-driver-registrar
    spec:
      serviceAccountName: csi-driver-registrar
      hostNetwork: true
      containers:
        - name: node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.2
          args:
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/huawei.csi.driver/csi.sock"
          imagePullPolicy: "IfNotPresent"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/huawei.csi.driver-reg.sock"]
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/huawei.csi.driver/
            type: Directory
