kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mypvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: mysc
  resources:
    requests:
      storage: 10Gi

